// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzaldOH0uVr2gf5G0pN89j5okrFLMaaMg',
    appId: '1:727471261439:web:6bea54fa042b0814d3eeca',
    messagingSenderId: '727471261439',
    projectId: 'lw11-12',
    authDomain: 'lw11-12.firebaseapp.com',
    storageBucket: 'lw11-12.firebasestorage.app',
    measurementId: 'G-81JLLVC5LL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3gLyyaas-9LaOOYUKuV1xREnpGDkpp9U',
    appId: '1:727471261439:android:18e4552a31d19464d3eeca',
    messagingSenderId: '727471261439',
    projectId: 'lw11-12',
    storageBucket: 'lw11-12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCph0zJGIYm1KrlsRTw9ehsnv3hSoKUQC4',
    appId: '1:727471261439:ios:41ad34d92d33e110d3eeca',
    messagingSenderId: '727471261439',
    projectId: 'lw11-12',
    storageBucket: 'lw11-12.firebasestorage.app',
    iosBundleId: 'com.example.lw1112',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCph0zJGIYm1KrlsRTw9ehsnv3hSoKUQC4',
    appId: '1:727471261439:ios:41ad34d92d33e110d3eeca',
    messagingSenderId: '727471261439',
    projectId: 'lw11-12',
    storageBucket: 'lw11-12.firebasestorage.app',
    iosBundleId: 'com.example.lw1112',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzaldOH0uVr2gf5G0pN89j5okrFLMaaMg',
    appId: '1:727471261439:web:a441c0e421a8b776d3eeca',
    messagingSenderId: '727471261439',
    projectId: 'lw11-12',
    authDomain: 'lw11-12.firebaseapp.com',
    storageBucket: 'lw11-12.firebasestorage.app',
    measurementId: 'G-HEHG1F3ZNV',
  );
}
